blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº Discussions Zone
    url: https://github.com/BITNP/BIThesis/discussions 
    about: |
      æœ‰ç–‘é—®æˆ–ä¸çŸ¥æ€æ ·æ“ä½œï¼Ÿï¼ˆè€Œéå‘ç°é”™è¯¯æˆ–æå‡ºéœ€æ±‚ï¼‰è¯·åœ¨è¿™é‡Œè®¨è®ºã€‚
      Do you have a question? (instead of a specific bug or feature request) Please discuss it here.
  - name: ğŸ§ QQç¾¤ 737548118
    url: https://jq.qq.com/?_wv=1027&k=KYDrmS5z
    about: |
      åªæƒ³é—®ä¸ªå°é—®é¢˜ï¼ŸLaTeXç¯å¢ƒå®‰è£…ä¸å¯¹ï¼Ÿå¯å»QQç¾¤èŠã€‚
      Just a small question? Weird LaTeX environment? Join and chat in the QQ group.
